display_errors = Off
log_errors = On
error_log = /var/log/php/error.log

expose_php = Off
session.cookie_httponly = 1
session.cookie_samesite = Strict
session.cookie_secure = 1
session.use_strict_mode = 1
session.use_only_cookies = 1

allow_url_fopen = Off
allow_url_include = Off
disable_functions = exec,passthru,shell_exec,system,proc_open,popen

upload_max_filesize = 2M
post_max_size = 4M
max_execution_time = 30
